### ISSUE TITLE
gem 이 등록되어 있지 않습니다

### ISSUE THREAD

**Issue by stadia** [iamport/iamport-rest-client-ruby#11]
gem search iamport 해도 나오지 않습니다.
https://rubygems.org/ 에 계정 하나 만들어서 등록해주시면 감사하겠습니다

굳이 필요하진 않겠지만 travis.org 에서 빌드를 돌려도 좋겠습니다

**Comment by G-ONL** [comment]
저도 설치에 어려움을 겪고 있는데 어떻게 해결하셨나요?? 

Gemfile에 넣고 bundle을 하면 인식은 하는데 파일이 생성이 안되네요 이후에 install을 하면 iamport를 찾을 수 없다고 Could not find a valid gem 'iamport' (>= 0) in any repository 이렇게 나오네요!

**Comment by stadia** [comment]
제가 fork 해놓은 프로젝트를 번들에 넣고 쓰셔도 되겠습니다.

**Comment by G-ONL** [comment]
휴일인데도 빠른답변 너무너무 감사합니다!! ^^ 

이어서 죄송하지만 ㅠㅠ
혹시 bundle show iamport를 했더니 /home/ec2-user/.rvm/gems/ruby-2.3.0/bundler/gems/iamport-rest-client-ruby-d1ba7fb79377 이렇게 나오면 설치에 성공한건가요?? 저위치에 들어가면 파일들이 다 있네요!

**Comment by stadia** [comment]
네. 제대로 설치 된 상태입니다

**Comment by jhsbeat** [comment]
@stadia Gem을 rubygems.org 에 publish 하였습니다. 
travis 환경은 별도의 이슈로 분리하여 진행하면 좋을 것 같은데 혹시 현재의 이슈는 close 가능 하실까요? ^^

**Comment by stadia** [comment]
감사합니다
