### ISSUE TITLE
Access_token 전달시 header에 포함하여 전송하도록 수정

### ISSUE THREAD

**Issue by ujuc** [iamport/iamport-rest-client-ruby#2]
`access_token`전달시 URL query 보다는 Header의 `Authorization`으로 token을 전송하도록 수정이 필요합니다.

 해당 내용 [github issue](https://github.com/iamport/iamport-rest-client/issues/2)

**Comment by jangbora** [comment]
보안의 측면에서 token이 URL에 노출되는 것보다 Authorization으로 ssl 암호화되어 전달되는 편이 맞을 것 같습니다. 
현재 URL query 와 Authorization모두 사용이 가능하고 Authorization을 우선적으로 처리하게 되어있는데 API서버의 입장에서도 URL query에 대한 지원은 중단하는 것이 맞을 것 같습니다.

**Comment by ujuc** [comment]
넵 그것이 맞는 것같아서 해당 내용을 작성해뒀습니다.

지금 구현되어있는 것을 변경하는 방법에 대해서 좀 더 찾아보고 해당 내용을 PR 걸어두도록 하겠습니다. :)

**Comment by ujuc** [comment]
해당 사항 반영완료
