### ISSUE TITLE
비인증결제모듈 사용정보를 찾을 수 없습니다.

### ISSUE THREAD

**Issue by viveki2it** [iamport/iamport-rest-client-ruby#23]
Hi,

I am getting below response when I user create_customer API. Could you please help someone to how to use it. Thanks!

#<HTTParty::Response:0x55d13acb11d0 parsed_response={"code"=>1, "message"=>"비인증결제모듈 사용정보를 찾을 수 없습니다.", "response"=>nil}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["application/json; charset=UTF-8"], "date"=>["Wed, 05 Dec 2018 16:42:39 GMT"], "server"=>["Apache/2.4.7 (Ubuntu)"], "content-length"=>["158"], "connection"=>["Close"]}>

Regards,
Vivek!

**Comment by jhsbeat** [comment]
It seems you’ve used invalid api_key or api_token. Could you please check it again?

**Comment by quy-q** [comment]
have you solved it, if so please help me
