### ISSUE TITLE
httparty gem 이 없다고 나옵니다.

### ISSUE THREAD

**Issue by kosick** [iamport/iamport-rest-client-ruby#5]
token 을 구하는 과정에서 HTTParty 젬을 사용하는 것 같은데 이 모듈이 같이 dependency 가 묶여있지 않아서 
사용못하는 에러가 발생할 수 있습니다. 
제가 사용하는 rails-api 서버에 추가로 gem "httparty" 를 추가하여 해결하였습니다.

레일즈 초보라 gem 을 어느 dependency 에 추가해야하는지는 잘 모르겠습니다.
능력자분께서 httparty 를 dependency 에 추가해주시면 감사하겠습니다.

**Comment by ujuc** [comment]
해당 내용은 gemspac에 적혀있습니다.

https://github.com/iamport/iamport-rest-client-ruby/blob/master/iamport.gemspec#L26

http://guides.rubygems.org/specification-reference/#add_runtime_dependency
