### ISSUE TITLE
Installation이 안돼요

### ISSUE THREAD

**Issue by ohnu93** [iamport/iamport-rest-client-ruby#7]
Gemfile에  `gem 'iamport', github: 'iamport/iamport-rest-client-ruby'`를 추가 후

`bundle install`을 하였더니 다음과 같은 에러가 발생합니다:

```
Fetching git://github.com/iamport/iamport-rest-client-ruby.git
sh: 1: git: not found
```

왜 추가가 안될까요...

**Comment by Jravvit** [comment]
번들러에서 깃을 찾지 못하는 상황인것 같은데요.
bundle install  하는 컴퓨터에 깃이 설치되어있는지 확인해보시고 설치가 안되어있다면 깃을 설치 하시고
설치가 되어있으시다면 업데이트 해보시기 바랍니다.

**Comment by ohnu93** [comment]
죄송합니다 다른 서버와 헷갈려서 깃이 깔려있는줄 알았는데 안깔려 있었습니다.
